version: "0.1"
user: himabindu.bandi20
key: 95pBacU70Lht4Ltd0ta1sD8VyoGn6BSAO1cmFJuWo1lZPRSoma
matrix: {classname: [SampleTest1, SampleTest2]}
testSuites: ['mvn -Dplatname=mac -Dmaven.repo.local=./.m2 -Dtest=$classname test surefire-report:report']
pre: [npm install playwright@1.23.0 --save-exact, mvn -Dmaven.repo.local=./.m2 -Dmaven.test.skip=true clean install]
preDirectives:
    commands: [npm install playwright@1.23.0 --save-exact, mvn -Dmaven.repo.local=./.m2 -Dmaven.test.skip=true clean install]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
post: [cat yaml/mac/junit_hyperexecute_matrix_sample.yaml]
postDirectives:
    commands: [cat yaml/mac/junit_hyperexecute_matrix_sample.yaml]
    shell: ""
    workingDirectory: ""
env:
    TARGET_OS: MacOS Catalina
jobLabel:
    - playwright-Junit
    - mac
    - matrix
runson: mac
concurrency: 2
globalTimeout: 150
tunnelOpts:
    testsPerTunnel: 10
testSuiteTimeout: 150
testSuiteStep: 150
cacheDirectories:
    - .m2
cacheKey: '{{ checksum "pom.xml" }}'
retryOnFailure: true
shell: bash
maxRetries: 1
jobID: d7644602-0ffe-42a4-8379-3c6a9e792d48
mergeArtifacts: true
uploadArtefacts:
    - name: Surefire-Report
      path:
        - target/surefire-reports/**
      email:
        to: []
        metaInfo: []
        linkValidity: 0
codeDirectory: hyperexecute-java-playwright-sample-main
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: null
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        resignApp: true
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
        mitmProxy: false
        networkHar: false
        artifacts: false
        otherApps: []
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: playwright
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: false
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: ""
    name: ""
    type: default
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
regionConfig: []
waitForArtefactsUpload: false
unzipPayload: false
projectpath: ""
accessibilityJob: false
slackChannel: ""
